import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.lg,
  },
  title: {
    fontSize: 18,
    marginBottom: Theme.spacing.sm,
    textAlign: 'center',
    color: Theme.colors.primary,
    fontWeight: '700',
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    color: Theme.colors.primary,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    fontSize: 15,
    backgroundColor: Theme.colors.surface,
    color: Theme.colors.text,
  },
  pedidosCount: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.white,
    backgroundColor: Theme.colors.primary,
    paddingVertical: 6,
    paddingHorizontal: Theme.spacing.lg,
    borderRadius: Theme.radius.pill,
    alignSelf: 'center',
    marginBottom: Theme.spacing.sm,
    marginTop: 2,
    ...Theme.shadow.xs,
  },
  pedidosCountNumber: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  table: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    ...Theme.shadow.xs,
  },
  tableRowHeader: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.dark,
    borderTopLeftRadius: Theme.radius.md,
    borderTopRightRadius: Theme.radius.md,
  },
  tableHeaderCell: {
    flex: 1,
    color: Theme.colors.white,
    fontWeight: '700',
    padding: Theme.spacing.sm,
    fontSize: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 36,
  },
  tableCell: {
    flex: 1,
    padding: Theme.spacing.sm,
    fontSize: 13,
    color: Theme.colors.dark,
    textAlign: 'center',
  },
  rowEven: { backgroundColor: Theme.colors.rowEven },
  rowOdd:  { backgroundColor: Theme.colors.rowOdd },
  rowUno:  { backgroundColor: Theme.colors.rowWarning },
  rowAmbos:{ backgroundColor: Theme.colors.rowSuccess },
  cellFactura: { color: Theme.colors.info, fontWeight: '700' },
  cellNota:    { color: Theme.colors.error, fontWeight: '700' },
  cellAmbos:   { color: Theme.colors.successDark, fontWeight: '700' },
  guiaItem: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    ...Theme.shadow.xs,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderLeftWidth: 3,
    borderLeftColor: Theme.colors.primary,
  },
  guiaItemTitle: {
    fontWeight: '700',
    color: Theme.colors.primary,
    fontSize: 15,
  },
  guiaItemDetail: {
    color: Theme.colors.muted,
    fontSize: 13,
  },
  guiaItemWarning: {
    color: Theme.colors.error,
    fontWeight: '700',
    fontSize: 13,
  },
  guiaItemDeshabilitada: {
    opacity: 0.5,
  },
  comentarioBox: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.lg,
    marginTop: Theme.spacing.md,
    ...Theme.shadow.xs,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  saveButton: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xxl,
    alignSelf: 'center',
    marginTop: Theme.spacing.md,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  saveButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  scanButton: {
    backgroundColor: Theme.colors.info,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xxl,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    alignSelf: 'center',
    ...Theme.shadow.xs,
  },
  scanButtonText: {
    color: Theme.colors.white,
    fontSize: 15,
    fontWeight: '700',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xxl,
    backgroundColor: Theme.colors.background,
  },
  backButtonText: {
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.md,
    fontWeight: '600',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: Theme.colors.error,
    fontWeight: '700',
    alignSelf: 'center',
    marginBottom: 6,
  },
  statusText: {
    marginTop: Theme.spacing.md,
    fontWeight: '600',
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 13,
  },
  emptyText: {
    color: Theme.colors.muted,
    textAlign: 'center',
  },
  cameraContainer: {
    width: '100%',
    height: 150,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.black,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  camera: {
    width: '100%',
    height: '100%',
  },
  cameraPermissionButton: {
    backgroundColor: Theme.colors.primary,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.md,
  },
  cameraPermissionButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
  },
});

export default styles;
