import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.lg,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.md,
    alignSelf: 'center',
    letterSpacing: -0.3,
  },
  guiaItem: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.sm,
  },
  guiaText: {
    fontWeight: '700',
    fontSize: 17,
    color: Theme.colors.primary,
  },
  guiaSubText: {
    color: Theme.colors.success,
    fontSize: 14,
    marginTop: 2,
    marginBottom: 4,
  },
  empty: {
    color: Theme.colors.muted,
    fontStyle: 'italic',
    alignSelf: 'center',
    marginTop: 40,
  },
  pedidosCount: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.white,
    backgroundColor: Theme.colors.success,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.pill,
    alignSelf: 'center',
    marginBottom: Theme.spacing.sm,
    marginTop: Theme.spacing.sm,
    ...Theme.shadow.xs,
  },
  pedidosCountNumber: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 20,
  },
  input: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Theme.colors.primary,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.xs,
    color: Theme.colors.text,
  },
  scanButton: {
    backgroundColor: Theme.colors.info,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: 28,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    alignSelf: 'center',
    ...Theme.shadow.xs,
  },
  scanButtonText: {
    color: Theme.colors.white,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  table: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.xl,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    ...Theme.shadow.xs,
  },
  tableRowHeader: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.success,
    borderTopLeftRadius: Theme.radius.lg,
    borderTopRightRadius: Theme.radius.lg,
  },
  tableHeaderCell: {
    flex: 1,
    color: Theme.colors.white,
    fontWeight: '700',
    padding: Theme.spacing.sm,
    fontSize: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 36,
  },
  tableCell: {
    flex: 1,
    padding: Theme.spacing.sm,
    fontSize: 13,
    color: Theme.colors.muted,
    textAlign: 'center',
  },
  rowEven:    { backgroundColor: Theme.colors.rowEven },
  rowOdd:     { backgroundColor: Theme.colors.rowOdd },
  rowChecked: { backgroundColor: Theme.colors.primary },
  rowUno:     { backgroundColor: Theme.colors.rowWarning },
  rowAmbos:   { backgroundColor: Theme.colors.rowSuccess },
  cellFactura: { color: Theme.colors.info, fontWeight: '700' },
  cellNota:    { color: Theme.colors.error, fontWeight: '700' },
  cellAmbos:   { color: Theme.colors.white, fontWeight: '700' },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xxl,
    backgroundColor: Theme.colors.background,
  },
  backButton: {
    marginTop: Theme.spacing.xxl,
    backgroundColor: Theme.colors.muted,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xxxl,
    borderRadius: Theme.radius.md,
    alignSelf: 'center',
    ...Theme.shadow.xs,
  },
  backButtonText: {
    color: Theme.colors.white,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  result: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.md,
    marginHorizontal: Theme.spacing.lg,
  },
  comentarioBox: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    marginTop: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  saveButton: {
    backgroundColor: Theme.colors.success,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.lg,
    paddingHorizontal: Theme.spacing.xxl,
    alignSelf: 'center',
    marginTop: -20,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  saveButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 16,
  },
  jsonBox: {
    backgroundColor: Theme.colors.surfaceAlt,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginTop: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.borderStrong,
    ...Theme.shadow.xs,
  },
  escobaButton: {
    backgroundColor: 'transparent',
    padding: Theme.spacing.xs,
    borderRadius: Theme.radius.pill,
    marginLeft: Theme.spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  labelCargadas: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.success,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.xs,
    alignSelf: 'center',
  },
  labelPendientes: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.error,
    marginTop: Theme.spacing.xl,
    marginBottom: Theme.spacing.xs,
    alignSelf: 'center',
  },
  guiaItemCargada: {
    backgroundColor: Theme.colors.successLight,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.success,
    ...Theme.shadow.xs,
  },
  guiaItemDeshabilitada: {
    opacity: 0.5,
  },
  deleteButton: {
    backgroundColor: Theme.colors.error,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    alignSelf: 'center',
    marginTop: Theme.spacing.md,
    ...Theme.shadow.xs,
  },
  deleteButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  cameraContainer: {
    width: '100%',
    height: 180,
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.black,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  camera: {
    width: '100%',
    height: '100%',
    borderRadius: Theme.radius.lg,
  },
});

export default styles;
