import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: Theme.colors.dark,
    marginBottom: Theme.spacing.md,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  label: {
    fontWeight: '600',
    color: Theme.colors.primary,
    marginTop: Theme.spacing.md,
    marginBottom: 4,
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  reportesList: {
    flex: 1,
  },
  reporteItem: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderLeftWidth: 3,
    ...Theme.shadow.sm,
  },
  reporteStatus: {
    fontWeight: '700',
    fontSize: 15,
  },
  reporteComentario: {
    color: Theme.colors.muted,
    fontSize: 13,
    marginTop: 3,
  },
  reporteCoordenadas: {
    color: Theme.colors.light,
    fontSize: 12,
    marginTop: 3,
  },
  reporteFecha: {
    color: Theme.colors.light,
    fontSize: 12,
    marginTop: 4,
    textAlign: 'right',
  },
  fabRow: {
    position: 'absolute',
    bottom: Theme.spacing.xl,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 20,
  },
  roundButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: Theme.spacing.lg,
    ...Theme.shadow.md,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    fontSize: 15,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
  },
  inputMultiline: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  selectRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: Theme.spacing.md,
  },
  selectOption: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.surface,
  },
  selectOptionText: {
    fontWeight: '600',
    fontSize: 14,
    color: Theme.colors.muted,
  },
  formButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Theme.spacing.md,
    gap: 8,
  },
  actionButton: {
    flex: 1,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    color: Theme.colors.white,
    fontWeight: '600',
    fontSize: 14,
  },
  cancelButton: {
    backgroundColor: Theme.colors.surfaceAlt,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cancelButtonText: {
    color: Theme.colors.muted,
    fontWeight: '600',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.lg,
  },
  modalContent: {
    width: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    ...Theme.shadow.lg,
  },
  headerSticky: {
    backgroundColor: Theme.colors.background,
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.sm,
    zIndex: 10,
  },
  floatingTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Theme.colors.dark,
    textAlign: 'center',
    letterSpacing: -0.2,
    backgroundColor: Theme.colors.background,
    paddingVertical: 8,
  },
  floatingSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.primary,
    textAlign: 'center',
    backgroundColor: Theme.colors.background,
    paddingVertical: 4,
  },
  reporteCliente: {
    fontWeight: '700',
    color: Theme.colors.dark,
    fontSize: 15,
    marginBottom: 2,
  },
  clienteItem: {
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  clienteItemSelected: {
    backgroundColor: Theme.colors.primaryLight,
  },
  clienteText: {
    fontSize: 15,
    color: Theme.colors.text,
  },
  selectedClienteLabel: {
    color: Theme.colors.success,
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    minHeight: 44,
    justifyContent: 'center',
  },
  coordenadasInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surfaceAlt,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
    gap: 6,
  },
  coordenadasText: {
    color: Theme.colors.muted,
    fontSize: 12,
    flex: 1,
  },
});

export default styles;
