import { StyleSheet, Dimensions, Platform } from 'react-native';
import Theme from '../constants/Theme';

const { width } = Dimensions.get('window');
const isSmallDevice = width < 375;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollContent: {
    padding: isSmallDevice ? Theme.spacing.lg : Theme.spacing.xxl,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xxl,
    backgroundColor: Theme.colors.background,
  },
  permissionText: {
    fontSize: 15,
    marginBottom: Theme.spacing.lg,
    textAlign: 'center',
    color: Theme.colors.muted,
  },
  title: {
    fontSize: isSmallDevice ? 22 : 26,
    fontWeight: '700',
    marginBottom: Theme.spacing.md,
    color: Theme.colors.primary,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  subtitle: {
    fontSize: isSmallDevice ? 13 : 15,
    marginBottom: Theme.spacing.xxl,
    color: Theme.colors.muted,
    textAlign: 'center',
    lineHeight: 20,
  },
  scanButton: {
    backgroundColor: Theme.colors.primary,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xxl,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.sm,
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
      android: { elevation: 2 },
    }),
  },
  scanButtonText: {
    color: Theme.colors.white,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  tableButton: {
    backgroundColor: Theme.colors.success,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.md,
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
      android: { elevation: 2 },
    }),
  },
  tableButtonText: {
    color: Theme.colors.white,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: Theme.colors.overlayLight,
    justifyContent: 'center',
    alignItems: 'center',
    padding: isSmallDevice ? Theme.spacing.lg : Theme.spacing.xxl,
  },
  modalContent: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: isSmallDevice ? Theme.spacing.xl : Theme.spacing.xxl,
    width: '100%',
    maxWidth: 500,
    maxHeight: '80%',
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 10 },
      android: { elevation: 6 },
    }),
  },
  modalTitle: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '700',
    marginBottom: Theme.spacing.md,
    color: Theme.colors.primary,
    alignSelf: 'center',
    textAlign: 'center',
  },
  modalDivider: {
    height: 1,
    backgroundColor: Theme.colors.border,
    marginVertical: Theme.spacing.md,
  },
  facturasList: { flex: 1 },
  facturasListContent: { paddingBottom: Theme.spacing.md },
  facturaItem: {
    marginBottom: Theme.spacing.md,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  facturaNumero: {
    fontWeight: '700',
    color: Theme.colors.primary,
    fontSize: 15,
  },
  facturaDescripcion: {
    color: Theme.colors.dark,
    fontSize: 13,
    marginTop: 2,
  },
  facturaDetalle: {
    color: Theme.colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  emptyState: {
    padding: Theme.spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateText: {
    fontSize: 15,
    color: Theme.colors.muted,
    textAlign: 'center',
  },
  modalButton: {
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    marginTop: Theme.spacing.sm,
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2 },
      android: { elevation: 2 },
    }),
  },
  modalCloseButton: { backgroundColor: Theme.colors.muted },
  sendButton:       { backgroundColor: Theme.colors.info },
  saveButton:       { backgroundColor: Theme.colors.success },
  closeButton:      { backgroundColor: Theme.colors.muted },
  cleanButton:      { backgroundColor: Theme.colors.error, marginTop: Theme.spacing.md },
  modalButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  modalError: {
    color: Theme.colors.error,
    marginBottom: Theme.spacing.md,
    alignSelf: 'center',
    fontWeight: '700',
    textAlign: 'center',
  },
  modalTable: {
    marginBottom: Theme.spacing.lg,
  },
  modalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    alignItems: 'center',
  },
  modalRowLabel: {
    fontWeight: '700',
    color: Theme.colors.dark,
    minWidth: 100,
    fontSize: isSmallDevice ? 13 : 15,
  },
  modalRowValue: {
    color: Theme.colors.muted,
    flex: 1,
    textAlign: 'right',
    fontSize: isSmallDevice ? 13 : 15,
  },
  buttonGroup: {
    width: '100%',
    marginTop: Theme.spacing.lg,
    marginBottom: Theme.spacing.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
  },
  cameraBox: {
    width: '100%',
    maxWidth: 400,
    height: isSmallDevice ? 180 : 220,
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.dark,
  },
  facturaDataContainer: {
    width: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: isSmallDevice ? Theme.spacing.md : Theme.spacing.lg,
    marginVertical: Theme.spacing.sm,
    borderLeftWidth: 4,
    borderLeftColor: Theme.colors.primary,
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 3 },
      android: { elevation: 1 },
    }),
  },
  cardTitle: {
    fontSize: isSmallDevice ? 16 : 18,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginBottom: 6,
    textAlign: 'center',
  },
  comentarioContainer: {
    marginTop: Theme.spacing.md,
  },
  comentarioLabel: {
    fontWeight: '700',
    color: Theme.colors.error,
    marginBottom: 6,
    fontSize: isSmallDevice ? 13 : 15,
  },
  comentarioInput: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm,
    padding: Theme.spacing.md,
    minHeight: 80,
    textAlignVertical: 'top',
    fontSize: 14,
    color: Theme.colors.text,
  },
  manualInputContainer: {
    width: '100%',
    marginBottom: Theme.spacing.md,
  },
  manualInputLabel: {
    fontWeight: '700',
    marginBottom: Theme.spacing.sm,
    color: Theme.colors.primary,
    fontSize: isSmallDevice ? 13 : 15,
  },
  manualInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  manualInput: {
    flex: 1,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: Theme.spacing.md,
    fontSize: 15,
    marginRight: Theme.spacing.sm,
    minHeight: 44,
    color: Theme.colors.text,
  },
  consultButton: {
    backgroundColor: Theme.colors.primary,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.lg,
    borderRadius: Theme.radius.md,
    minHeight: 44,
    justifyContent: 'center',
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2 },
      android: { elevation: 2 },
    }),
  },
  consultButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
});

export default styles;
