import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  headerContainer: {
    padding: Theme.spacing.lg,
    backgroundColor: Theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.md,
    textAlign: 'center',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginRight: Theme.spacing.sm,
    backgroundColor: Theme.colors.surface,
    fontSize: 15,
    color: Theme.colors.text,
  },
  btn: {
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.lg,
    borderRadius: Theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  btnPrimary: { backgroundColor: Theme.colors.primary },
  btnInfo:    { backgroundColor: Theme.colors.info },
  btnError:   { backgroundColor: Theme.colors.error },
  btnSuccess: { backgroundColor: Theme.colors.success },
  btnWarning: { backgroundColor: Theme.colors.warning },
  btnDisabled:{ backgroundColor: Theme.colors.light },
  btnText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 14,
  },
  scrollContent: {
    padding: Theme.spacing.lg,
  },
  errorText: {
    color: Theme.colors.error,
    textAlign: 'center',
    marginVertical: Theme.spacing.md,
    fontWeight: '600',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Theme.spacing.sm,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Theme.colors.error,
    marginRight: 6,
  },
  liveText: {
    color: Theme.colors.error,
    fontWeight: '700',
    fontSize: 12,
  },
  table: {
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.surface,
    marginBottom: Theme.spacing.xl,
    ...Theme.shadow.xs,
  },
  tableRowHeader: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.dark,
    padding: Theme.spacing.sm,
  },
  tableHeaderCell: {
    flex: 1,
    color: Theme.colors.white,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: 'row',
    padding: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    color: Theme.colors.dark,
  },
  rowEven:  { backgroundColor: Theme.colors.rowEven },
  rowOdd:   { backgroundColor: Theme.colors.rowOdd },
  rowUno:   { backgroundColor: Theme.colors.rowWarning },
  rowAmbos: { backgroundColor: Theme.colors.rowSuccess },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.dark,
    marginVertical: Theme.spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  noData: {
    textAlign: 'center',
    color: Theme.colors.muted,
    marginVertical: Theme.spacing.md,
    fontStyle: 'italic',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.lg,
    gap: Theme.spacing.sm,
  },
  cameraBox: {
    height: 280,
    overflow: 'hidden',
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.lg,
    backgroundColor: Theme.colors.black,
    position: 'relative',
  },
  camera: { flex: 1 },
  closeCamBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeCamText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 16,
  },
  manualScanBox: {
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  manualInput: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
    fontSize: 15,
    color: Theme.colors.text,
  },
  actionRow: {
    flexDirection: 'row',
    marginBottom: Theme.spacing.lg,
    gap: Theme.spacing.sm,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: Theme.spacing.md,
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.pill,
  },
  badgeSuccess: { backgroundColor: Theme.colors.success },
  badgeWarning: { backgroundColor: Theme.colors.warning },
  statusText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  summaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  feedbackModalContent: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.xxxl,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    ...Theme.shadow.lg,
    borderWidth: 3,
  },
  borderSuccess: { borderColor: Theme.colors.success },
  borderWarning: { borderColor: Theme.colors.warning },
  borderError:   { borderColor: Theme.colors.error },
  feedbackTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: Theme.colors.dark,
    marginTop: Theme.spacing.md,
    textAlign: 'center',
  },
  feedbackValue: {
    fontSize: 26,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginVertical: Theme.spacing.md,
  },
  feedbackMessage: {
    fontSize: 16,
    color: Theme.colors.muted,
    textAlign: 'center',
    marginBottom: Theme.spacing.xxl,
    lineHeight: 24,
  },
  feedbackBtn: {
    width: '100%',
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusIndicatorRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusIndicatorText: {
    fontSize: 12,
    color: Theme.colors.dark,
    fontWeight: '500',
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  cameraErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.xl,
  },
  cameraErrorText: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.colors.error,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
  },
  cameraErrorDetail: {
    fontSize: 13,
    color: Theme.colors.muted,
    textAlign: 'center',
    marginBottom: Theme.spacing.md,
  },
  dataContainer: {
    marginBottom: Theme.spacing.md,
  },
});

export default styles;
