import { StyleSheet, Dimensions } from 'react-native';
import Theme from '../constants/Theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: Theme.spacing.xl,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: '4%',
    paddingTop: Theme.spacing.xxl,
    width: '100%',
    minHeight: '100%',
  },
  subtitle: {
    fontSize: 22,
    color: Theme.colors.dark,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: -0.3,
    textAlign: 'left',
    width: '100%',
  },
  welcomeText: {
    fontSize: 13,
    color: Theme.colors.muted,
    marginBottom: Theme.spacing.xl,
    textAlign: 'left',
    width: '100%',
  },
  syncRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.xxl,
    width: '100%',
    maxWidth: 500,
  },
  syncButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surface,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.lg,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.sm,
    minWidth: 140,
  },
  syncButtonText: {
    color: Theme.colors.primary,
    fontWeight: '600',
    fontSize: 13,
  },
  syncIcon: {
    marginRight: 6,
  },
  clientesInfoBox: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    minWidth: 100,
    maxWidth: SCREEN_WIDTH * 0.45,
    ...Theme.shadow.sm,
  },
  infoTitle: {
    color: Theme.colors.muted,
    fontWeight: '600',
    fontSize: 11,
    marginBottom: 2,
    textAlign: 'center',
    width: '100%',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoNumber: {
    color: Theme.colors.primary,
    fontWeight: '700',
    fontSize: 32,
    marginVertical: 2,
    textAlign: 'center',
    width: '100%',
  },
  infoSubtitle: {
    color: Theme.colors.light,
    fontSize: 11,
    textAlign: 'center',
    width: '100%',
  },
  menuButton: {
    marginLeft: 15,
  },
  syncingOverlay: {
    position: 'absolute',
    top: '40%',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 10,
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingVertical: 40,
    width: '100%',
  },
  syncingText: {
    marginTop: Theme.spacing.lg,
    fontSize: 16,
    color: Theme.colors.primary,
    fontWeight: '600',
    textAlign: 'center',
    width: '100%',
  },
  syncDetailBox: {
    marginTop: Theme.spacing.xxl,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.lg,
    width: '100%',
    maxWidth: 500,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.sm,
  },
  syncDetailTitle: {
    fontWeight: '600',
    color: Theme.colors.primary,
    fontSize: 15,
    marginBottom: Theme.spacing.sm,
    textAlign: 'center',
    width: '100%',
  },
  syncDetailItem: {
    fontSize: 14,
    color: Theme.colors.text,
    marginBottom: 4,
    textAlign: 'center',
    width: '100%',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.primary,
    paddingVertical: Theme.spacing.lg,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.lg,
    marginTop: Theme.spacing.md,
    width: '100%',
    maxWidth: 500,
    ...Theme.shadow.sm,
  },
  btnIconContainer: {
    width: 38,
    height: 38,
    borderRadius: Theme.radius.md,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  actionButtonText: {
    color: Theme.colors.white,
    fontWeight: '600',
    fontSize: 16,
    flex: 1,
  },
  btnIcon: {
    marginRight: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xxl,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    ...Theme.shadow.lg,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.dark,
    marginBottom: Theme.spacing.sm,
  },
  modalSubtitle: {
    fontSize: 13,
    color: Theme.colors.muted,
    textAlign: 'center',
    marginBottom: Theme.spacing.xl,
  },
  discountInput: {
    width: '100%',
    height: 52,
    borderWidth: 1.5,
    borderColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.xxl,
    backgroundColor: Theme.colors.surfaceAlt,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: Theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  confirmButton: {
    backgroundColor: Theme.colors.primary,
  },
  cancelButtonText: {
    color: Theme.colors.muted,
    fontWeight: '600',
    fontSize: 14,
  },
  confirmButtonText: {
    color: Theme.colors.white,
    fontWeight: '600',
    fontSize: 14,
  },
  kpiLoadingContainer: {
    marginTop: Theme.spacing.xl,
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  kpiLoadingText: {
    marginTop: 10,
    fontSize: 15,
    color: Theme.colors.primary,
    fontWeight: '600',
  },
  kpiContainer: {
    marginTop: Theme.spacing.md,
    width: '100%',
    maxWidth: 500,
    paddingBottom: Theme.spacing.xl,
  },
  kpiHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.xl,
    width: '100%',
  },
  kpiHeaderBox: {
    flex: 1,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginHorizontal: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  kpiHeaderLabel: {
    fontSize: 11,
    color: Theme.colors.muted,
    marginBottom: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  kpiHeaderValue: {
    fontSize: 22,
    fontWeight: '700',
    color: Theme.colors.primary,
  },
  kpiNewSection: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xxl,
    marginBottom: Theme.spacing.lg,
    width: '100%',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.sm,
  },
  kpiTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
  },
  kpiNewSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Theme.colors.dark,
    marginLeft: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  kpiDataItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm,
  },
  kpiDataLabel: {
    fontSize: 14,
    color: Theme.colors.muted,
    flex: 1,
    fontWeight: '400',
  },
  kpiDataValue: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.text,
    textAlign: 'right',
  },
  kpiDivider: {
    height: 1,
    backgroundColor: Theme.colors.border,
    width: '100%',
  },
});

export default styles;
