import { StyleSheet, Dimensions } from 'react-native';
import Theme from '../constants/Theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Theme.spacing.lg,
    paddingVertical: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  backButton: {
    padding: Theme.spacing.sm,
    marginLeft: -8,
    marginRight: 4,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.dark,
    lineHeight: 18,
  },
  headerSubtitle: {
    fontSize: 11,
    color: Theme.colors.muted,
    maxWidth: SCREEN_WIDTH * 0.6,
  },
  searchHeaderButton: {
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.sm,
    borderRadius: Theme.radius.pill,
  },
  mainScroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: Theme.spacing.lg,
    paddingBottom: 100,
  },
  clientScrollContent: {
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.sm,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sectionSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: Theme.colors.light,
  },
  discountsScroll: {
    marginBottom: Theme.spacing.lg,
  },
  discountsContent: {
    paddingHorizontal: Theme.spacing.lg,
    paddingBottom: 4,
  },
  discountCard: {
    width: 128,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    marginRight: Theme.spacing.md,
    ...Theme.shadow.xs,
  },
  discountTag: {
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 4,
  },
  discountValue: {
    fontSize: 22,
    fontWeight: '900',
  },
  searchContainer: {
    paddingHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surface,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.pill,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
    ...Theme.shadow.xs,
  },
  searchIcon: {
    marginRight: Theme.spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: Theme.colors.text,
  },
  categoryContainer: {
    marginBottom: Theme.spacing.lg,
  },
  categoryContent: {
    paddingHorizontal: Theme.spacing.lg,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: Theme.spacing.lg,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.pill,
    backgroundColor: Theme.colors.surface,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  categoryChipSelected: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: Theme.colors.muted,
  },
  categoryTextSelected: {
    color: Theme.colors.white,
  },
  productsContainer: {
    paddingHorizontal: Theme.spacing.lg,
  },
  productCard: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    marginHorizontal: Theme.spacing.lg,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  productMainInfo: {
    flexDirection: 'row',
    gap: Theme.spacing.lg,
  },
  productImageContainer: {
    width: 84,
    height: 84,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  imageBadgeContainer: {
    position: 'absolute',
    top: 4,
    left: 4,
    right: 4,
    flexDirection: 'column',
    gap: 4,
  },
  productImageBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Theme.radius.pill,
    borderWidth: 1,
    alignSelf: 'flex-start',
    ...Theme.shadow.xs,
  },
  imageBadgeText: {
    fontSize: 9,
    fontWeight: '900',
  },
  productDetails: {
    flex: 1,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.dark,
    lineHeight: 18,
    marginBottom: 4,
  },
  productExpiry: {
    fontSize: 11,
    color: Theme.colors.light,
    marginBottom: Theme.spacing.sm,
  },
  productPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productPrice: {
    fontSize: 17,
    fontWeight: '700',
    color: Theme.colors.primary,
  },
  stockContainer: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 2,
  },
  stockItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stockLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: Theme.colors.muted,
  },
  stockValue: {
    fontSize: 11,
    fontWeight: '700',
    color: Theme.colors.primary,
    minWidth: 20,
    textAlign: 'right',
  },
  stockAgotadoText: {
    color: Theme.colors.error,
  },
  productActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Theme.spacing.md,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  quantitySection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.muted,
    marginRight: Theme.spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.pill,
    padding: 4,
  },
  quantityButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadow.xs,
  },
  quantityButtonActive: {
    backgroundColor: Theme.colors.primary,
  },
  quantityText: {
    width: 40,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  subtotalSection: {
    alignItems: 'flex-end',
  },
  subtotalLabel: {
    fontSize: 10,
    color: Theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  subtotalValue: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  footerNoteContainerFixed: {
    paddingHorizontal: Theme.spacing.xxl,
    marginTop: Theme.spacing.sm,
    marginBottom: 100,
  },
  footerNote: {
    fontSize: 11,
    color: Theme.colors.light,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: Theme.spacing.lg,
    backgroundColor: Theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  summaryInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  summaryLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  summaryAmount: {
    fontSize: 20,
    fontWeight: '900',
    color: Theme.colors.text,
  },
  summaryUnits: {
    fontSize: 11,
    color: Theme.colors.muted,
    fontWeight: '500',
  },
  savingsTag: {
    backgroundColor: Theme.colors.successLight,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.pill,
  },
  savingsText: {
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.successDark,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    height: 52,
    borderRadius: Theme.radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.muted,
  },
  orderButton: {
    flex: 2,
    backgroundColor: Theme.colors.primary,
    height: 52,
    borderRadius: Theme.radius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...Theme.shadow.sm,
  },
  orderButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.white,
  },
  fab: {
    position: 'absolute',
    bottom: Theme.spacing.xxl,
    right: Theme.spacing.xxl,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadow.md,
  },
  fabIconContainer: {
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: Theme.colors.error,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: Theme.colors.primary,
  },
  badgeText: {
    color: Theme.colors.white,
    fontSize: 10,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Theme.colors.background,
    borderTopLeftRadius: Theme.radius.xxl,
    borderTopRightRadius: Theme.radius.xxl,
    height: '90%',
    flexDirection: 'column',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Theme.spacing.xxl,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    backgroundColor: Theme.colors.surface,
    borderTopLeftRadius: Theme.radius.xxl,
    borderTopRightRadius: Theme.radius.xxl,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  closeButton: {
    padding: 4,
  },
  modalSubtitle: {
    fontSize: 12,
    color: Theme.colors.muted,
    fontWeight: '500',
  },
  detailScrollContent: {
    padding: Theme.spacing.xxl,
  },
  detailImageContainer: {
    width: '100%',
    height: 240,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.xl,
    marginBottom: Theme.spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    overflow: 'hidden',
    position: 'relative',
  },
  detailImage: {
    width: '90%',
    height: '90%',
  },
  detailAgotadoBadge: {
    position: 'absolute',
    backgroundColor: Theme.colors.error,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
  },
  detailAgotadoText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  detailInfoSection: {
    gap: Theme.spacing.xl,
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Theme.colors.dark,
    lineHeight: 28,
  },
  detailMetaData: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  detailMetaItem: {
    alignItems: 'center',
    flex: 1,
  },
  detailMetaLabel: {
    fontSize: 10,
    color: Theme.colors.muted,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  detailMetaValue: {
    fontSize: 13,
    color: Theme.colors.dark,
    fontWeight: '700',
  },
  detailPriceSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailPriceLabel: {
    fontSize: 11,
    color: Theme.colors.muted,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailPriceValue: {
    fontSize: 28,
    fontWeight: '900',
    color: Theme.colors.primary,
  },
  detailBadgeRow: {
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-end',
  },
  detailStockSection: {
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    paddingTop: Theme.spacing.xl,
  },
  detailSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: Theme.spacing.lg,
  },
  detailStockGrid: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
  },
  detailStockCard: {
    flex: 1,
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  detailStockWarehouse: {
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.muted,
    marginBottom: Theme.spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailStockLarge: {
    fontSize: 24,
    fontWeight: '900',
    color: Theme.colors.primary,
  },
  detailStockUnit: {
    fontSize: 9,
    color: Theme.colors.light,
    fontWeight: '700',
  },
  detailTotalStock: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  detailTotalLabel: {
    fontSize: 12,
    color: Theme.colors.muted,
    fontWeight: '600',
  },
  detailTotalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  detailActionFooter: {
    padding: Theme.spacing.xxl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    backgroundColor: Theme.colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.lg,
  },
  detailQuantityWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.lg,
    padding: 6,
  },
  detailQuantityBtn: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadow.xs,
  },
  detailQuantityBtnActive: {
    backgroundColor: Theme.colors.primary,
  },
  detailQuantityInput: {
    width: 60,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  detailSubtotalWrapper: {
    flex: 1,
    alignItems: 'flex-end',
  },
  detailSubtotalLabel: {
    fontSize: 11,
    color: Theme.colors.muted,
    fontWeight: '700',
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailSubtotalValue: {
    fontSize: 20,
    fontWeight: '900',
    color: Theme.colors.primary,
  },
  cartSection: {
    backgroundColor: Theme.colors.surface,
    paddingVertical: Theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  cartDiscountsScroll: {
    paddingLeft: Theme.spacing.xxl,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
  },
  cartListContent: {
    padding: Theme.spacing.xxl,
    paddingBottom: Theme.spacing.xxl,
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...Theme.shadow.xs,
  },
  cartItemInfo: {
    flex: 1,
    marginRight: Theme.spacing.lg,
  },
  cartItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.dark,
    marginBottom: 2,
  },
  cartItemPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cartItemPrice: {
    fontSize: 13,
    fontWeight: '400',
    color: Theme.colors.muted,
  },
  cartItemBadges: {
    flexDirection: 'row',
    gap: 4,
  },
  miniBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    borderWidth: 1,
  },
  miniCategoryBadge: {
    backgroundColor: Theme.colors.warningLight,
    borderColor: Theme.colors.warning,
  },
  miniLineBadge: {
    backgroundColor: Theme.colors.successLight,
    borderColor: Theme.colors.success,
  },
  miniBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: Theme.colors.dark,
  },
  cartQuantitySection: {
    alignItems: 'flex-end',
    gap: 4,
  },
  quantitySelectorSm: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.sm,
    padding: 2,
  },
  cartItemSubtotal: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.primary,
  },
  quantityButtonSm: {
    width: 26,
    height: 26,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonActiveSm: {
    backgroundColor: Theme.colors.primary,
  },
  quantityTextSm: {
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 6,
    color: Theme.colors.dark,
    textAlign: 'center',
    minWidth: 20,
  },
  modalFooter: {
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    paddingBottom: 34,
  },
  summaryTable: {
    marginBottom: Theme.spacing.lg,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.dark,
  },
  totalFinalRow: {
    marginTop: Theme.spacing.sm,
    paddingTop: Theme.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Theme.colors.dark,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  totalFinalValue: {
    fontSize: 24,
    fontWeight: '900',
    color: Theme.colors.primary,
  },
  checkoutButton: {
    backgroundColor: Theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Theme.spacing.lg,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.lg,
    gap: 10,
    ...Theme.shadow.sm,
  },
  checkoutButtonText: {
    color: Theme.colors.white,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  checkoutButtonDisabled: {
    backgroundColor: Theme.colors.light,
    shadowOpacity: 0,
    elevation: 0,
  },
  emptyCartText: {
    textAlign: 'center',
    color: Theme.colors.muted,
    marginTop: 40,
    fontSize: 15,
  },
  clientAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: Theme.colors.white,
  },
  clientCard: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.surface,
    marginHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    ...Theme.shadow.sm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  clientAvatarContainer: {
    width: 52,
    height: 52,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Theme.spacing.md,
  },
  clientContent: {
    flex: 1,
  },
  clientMainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  clientName: {
    fontSize: 15,
    fontWeight: '700',
    color: Theme.colors.dark,
    flex: 1,
    marginRight: Theme.spacing.sm,
  },
  clientDivider: {
    height: 1,
    backgroundColor: Theme.colors.border,
    marginBottom: Theme.spacing.sm,
  },
  clientDetailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    alignItems: 'center',
  },
  clientDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  clientDetailValue: {
    fontSize: 12,
    color: Theme.colors.muted,
  },
  clientDiscountTag: {
    backgroundColor: Theme.colors.warningLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.warning,
  },
  clientDiscountText: {
    fontSize: 10,
    fontWeight: '700',
    color: Theme.colors.warning,
  },
  clientStatusBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    opacity: 0.9,
  },
  globalDiscountBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.successLight,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.lg,
    marginHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.success,
    gap: Theme.spacing.sm,
  },
  globalDiscountText: {
    fontSize: 12,
    fontWeight: '600',
    color: Theme.colors.successDark,
  },
});

export default styles;
