import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: Theme.spacing.lg,
    backgroundColor: Theme.colors.background,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: Theme.spacing.lg,
    color: Theme.colors.primary,
    letterSpacing: -0.2,
  },
  button: {
    backgroundColor: Theme.colors.primary,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.lg,
    ...Theme.shadow.xs,
  },
  buttonText: {
    color: Theme.colors.white,
    fontSize: 15,
    textAlign: 'center',
    fontWeight: '600',
  },
  error: {
    color: Theme.colors.error,
    marginVertical: Theme.spacing.sm,
    fontWeight: '500',
  },
  guiaBlock: {
    marginBottom: Theme.spacing.lg,
    padding: Theme.spacing.sm,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderLeftWidth: 3,
    borderLeftColor: Theme.colors.primary,
    ...Theme.shadow.xs,
  },
  guiaHeaderTouchable: { paddingVertical: Theme.spacing.sm },
  guiaHeader: {
    fontSize: 15,
    fontWeight: '700',
    color: Theme.colors.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    width: '95%',
    maxHeight: '90%',
    ...Theme.shadow.lg,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: Theme.spacing.md,
    color: Theme.colors.primary,
    textAlign: 'center',
  },
  closeModalButton: {
    marginTop: Theme.spacing.lg,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    alignItems: 'center',
  },
  closeModalButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  renglonesTable: {
    marginTop: Theme.spacing.sm,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.sm,
    padding: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  renglonesTitle: {
    fontWeight: '700',
    marginBottom: 4,
    color: Theme.colors.primary,
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  table: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.lg,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    ...Theme.shadow.xs,
  },
  tableRowHeader: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.dark,
    borderTopLeftRadius: Theme.radius.md,
    borderTopRightRadius: Theme.radius.md,
  },
  tableHeaderCell: {
    flex: 1,
    color: Theme.colors.white,
    fontWeight: '700',
    padding: Theme.spacing.sm,
    fontSize: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 36,
  },
  tableCell: {
    flex: 1,
    padding: Theme.spacing.sm,
    fontSize: 13,
    color: Theme.colors.text,
    textAlign: 'center',
  },
  rowEven:  { backgroundColor: Theme.colors.rowEven },
  rowOdd:   { backgroundColor: Theme.colors.rowOdd },
  rowUno:   { backgroundColor: Theme.colors.rowWarning },
  rowAmbos: { backgroundColor: Theme.colors.rowSuccess },
  renglonCampo: { fontSize: 13, marginBottom: 1 },
  scanBox: {
    marginTop: Theme.spacing.lg,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  scanTitle: {
    fontWeight: '700',
    fontSize: 15,
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.sm,
  },
  scanInput: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.sm,
    fontSize: 15,
    width: '90%',
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    color: Theme.colors.text,
  },
  scanButton: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.lg,
    marginTop: 4,
    ...Theme.shadow.xs,
  },
  scanButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 14,
  },
  scanError: {
    color: Theme.colors.error,
    marginTop: 6,
    fontSize: 13,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 14,
    zIndex: 10,
    backgroundColor: Theme.colors.background,
    borderRadius: 16,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    ...Theme.shadow.xs,
  },
  closeButtonText: {
    fontSize: 20,
    color: Theme.colors.primary,
    fontWeight: '700',
  },
  cameraContainer: {
    width: '100%',
    height: 220,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
  },
  cameraView: {
    flex: 1,
    borderRadius: Theme.radius.md,
  },
  closeScannerButton: {
    position: 'absolute',
    top: 12,
    right: Theme.spacing.lg,
    zIndex: 20,
    backgroundColor: Theme.colors.background,
    borderRadius: 16,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    ...Theme.shadow.xs,
  },
  closeScannerText: {
    fontSize: 16,
    color: Theme.colors.error,
    fontWeight: '700',
  },
  scannerLabel: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  comentarioInput: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.sm,
    fontSize: 14,
    width: '90%',
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    minHeight: 40,
    maxHeight: 80,
    color: Theme.colors.text,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    marginBottom: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 6,
    color: Theme.colors.text,
    backgroundColor: 'transparent',
  },
});

export default styles;
