import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  label: {
    fontWeight: '600',
    color: Theme.colors.primary,
    marginTop: Theme.spacing.md,
    marginBottom: 4,
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  gestionesList: {
    flex: 1,
  },
  gestionItem: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderLeftWidth: 3,
    borderLeftColor: Theme.colors.primary,
    ...Theme.shadow.sm,
  },
  gestionCliente: {
    fontWeight: '700',
    color: Theme.colors.text,
    fontSize: 15,
  },
  gestionInfo: {
    color: Theme.colors.primary,
    fontSize: 13,
    marginTop: 3,
  },
  gestionDesc: {
    color: Theme.colors.muted,
    fontSize: 13,
    marginTop: 3,
  },
  gestionFecha: {
    color: Theme.colors.light,
    fontSize: 12,
    marginTop: 4,
    textAlign: 'right',
  },
  fabRow: {
    position: 'absolute',
    bottom: Theme.spacing.xl,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 20,
  },
  roundButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: Theme.spacing.lg,
    ...Theme.shadow.md,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    fontSize: 15,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  clienteItem: {
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  clienteItemSelected: {
    backgroundColor: Theme.colors.primaryLight,
  },
  clienteText: {
    fontSize: 15,
    color: Theme.colors.text,
  },
  selectedClienteLabel: {
    color: Theme.colors.success,
    marginBottom: Theme.spacing.sm,
    marginTop: Theme.spacing.sm,
    fontSize: 14,
    fontWeight: '600',
  },
  radioGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: Theme.spacing.lg,
  },
  radioCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    marginRight: 6,
    backgroundColor: Theme.colors.surface,
  },
  radioCircleSelected: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  radioLabel: {
    fontSize: 14,
    color: Theme.colors.text,
  },
  formButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Theme.spacing.md,
    gap: 8,
  },
  actionButton: {
    flex: 1,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    ...Theme.shadow.xs,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    color: Theme.colors.white,
    fontWeight: '600',
    fontSize: 14,
  },
  cancelButton: {
    backgroundColor: Theme.colors.surfaceAlt,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cancelButtonText: {
    color: Theme.colors.muted,
    fontWeight: '600',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.lg,
  },
  modalContent: {
    width: '100%',
    maxHeight: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    ...Theme.shadow.lg,
  },
  inputIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  inputIcon: {
    marginRight: Theme.spacing.sm,
  },
  floatingTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Theme.colors.text,
    textAlign: 'center',
    letterSpacing: -0.2,
    backgroundColor: Theme.colors.background,
    paddingVertical: 8,
  },
  floatingSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.colors.primary,
    textAlign: 'center',
    backgroundColor: Theme.colors.background,
    paddingVertical: 4,
  },
  headerSticky: {
    backgroundColor: Theme.colors.background,
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.sm,
    zIndex: 10,
  },
  detalleCloseButton: {
    backgroundColor: Theme.colors.primary,
    marginTop: Theme.spacing.xxl,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xxxl,
    alignSelf: 'center',
    ...Theme.shadow.sm,
  },
  detalleCloseButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    overflow: 'hidden',
    minHeight: 44,
    justifyContent: 'center',
  },
});

export default styles;
